name: Run Foundry Test with Yarn

on: [push]

jobs:
  test_foundry_yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - name: NPM Install
        run: npm install
      - name: Run Forge Test
        run: forge test