name: Run Foundry Test with Yarn

on: [push]

jobs:
  test_foundry_yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 20
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - name: Yarn Install
        run: yarn
      - name: Run Forge Test
        run: forge test