name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: NPM Clean Install
        run: npm ci
      - name: Run test
        run: npm run test