name: Dependencies check NPM

on:
  push:
  workflow_dispatch:

jobs:
  dependencies_check_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: NPM Install
        run: npm i
      - name: NPM Outdated
        run: npm outdated
