name: Prettier

on:
  pull_request:
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Setup Node v16
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write src/
          only_changed: True