name: Prettier and TSLint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: NPM Clean Install
        run: npm ci
      - name: Run Prettier
        run: npx prettier --write src/
      - name: Run TS Linter
        run: npm run lint:fix