name: TSLint

on:
  pull_request:
  workflow_dispatch:

jobs:
  tslint:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - name: NPM Clean Install
        run: npm ci
      - name: TSLint
        uses: mooyoul/tslint-actions@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: 'src/*.ts'
